# Generated by Django 6.0.6 on 2026-06-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_remove_room_is_active_room_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='meeting_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
