# Generated by Django 6.0.6 on 2026-06-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_room_meeting_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='participant_ids',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
