# Generated by Django 6.0.6 on 2026-06-23 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_add_room_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='participant_ids',
        ),
        migrations.AddField(
            model_name='roommember',
            name='cloudflare_participant_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='roommember',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='room.room'),
        ),
    ]
