# Generated by Django 6.0.6 on 2026-06-27 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_bug002_room_member_fixes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomJoinRequest',
        ),
    ]
