# Generated by Django 6.0.6 on 2026-06-27 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_delete_roomjoinrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomMember',
        ),
    ]
