# Generated by Django 6.0.6 on 2026-06-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0009_delete_roommember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='room',
            name='max_members',
        ),
        migrations.RemoveField(
            model_name='room',
            name='role_configuration',
        ),
        migrations.RemoveField(
            model_name='room',
            name='scheduled_at',
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('playing', 'Playing'), ('finished', 'Finished')], default='playing', max_length=10),
        ),
    ]
