### GET request to example server
POST http://localhost:8000/api/accounts/register/
Content-Type: application/json

{
  "email": "anas1@gmail.com",
  "first_name": "Anas",
  "username": "anas1",
  "password": "Anas775995183"
}

###
