# Generated by Django 6.0.6 on 2026-06-20 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0002_remove_room_is_active_room_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('night', 'Night'), ('day', 'Day'), ('discussion', 'Discussion'), ('voting', 'Voting'), ('ended', 'Ended')], default='night', max_length=12)),
                ('round_number', models.PositiveSmallIntegerField(default=1)),
                ('night_actions', models.JSONField(blank=True, default=dict)),
                ('winner', models.CharField(blank=True, choices=[('mafia', 'Mafia'), ('villagers', 'Villagers'), ('draw', 'Draw')], max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_session', to='room.room')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('mafia', 'Mafia'), ('detective', 'Detective'), ('doctor', 'Doctor'), ('villager', 'Villager')], max_length=12)),
                ('is_alive', models.BooleanField(default=True)),
                ('won', models.BooleanField(blank=True, null=True)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gamesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'game_session')},
            },
        ),
        migrations.AddField(
            model_name='gamesession',
            name='players',
            field=models.ManyToManyField(related_name='game_sessions', through='game.Participant', to=settings.AUTH_USER_MODEL),
        ),
    ]
